language: node_js
node_js:
  - 10
script:
  - npm install
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local-dir: dist/
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
