AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs10.x
  Api:
    # enable CORS; to make more specific, change the origin wildcard
    # to a particular domain name, e.g. "'www.example.com'"
    Cors:
      AllowOrigin: "'http://localhost:8080'"
    BinaryMediaTypes:
      - image~1gif
      - image~1png
      - image~1jpeg
      - application/octet-stream
      - multipart/form-data

Resources:
  test:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
      CodeUri: app/
      Handler: test.test
      Events:
        Building:
          Type: Api
          Properties:
            Path: /test
            Method: get
